### ISSUE TITLE
Smaller Hero/CTA area

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_INOSENCIO#10]
I tried to drastically reduce the Hero/CTA area and while it overall looks nice at about `15em` (`240px`) tall, the background image doesn't fit nicely no matter what I do.

I think straight up centering horizontally and vertically looks best, but it may be even better to try another image.

We had talked about making these areas smaller, so I wanted to give it a shot. This _is not_ on Staging, but I do have screenshots below.

Current (`background-position: top left;`, the default state)
![image](https://user-images.githubusercontent.com/7770631/30225206-a25180b4-949f-11e7-84dc-99947a089aac.png)

`background-position: center;`
![image](https://user-images.githubusercontent.com/7770631/30225132-5eae7eb6-949f-11e7-81d6-a5043e737f22.png)

`background-position: bottom center;`
![image](https://user-images.githubusercontent.com/7770631/30225166-7a435598-949f-11e7-8bcf-996b8436f9dd.png)

**Comment by BigActual** [comment]
The only one that reads well is the first. Only because the roof is creating a nice backdrop for the white button. Otherwise, 1 is bad. Who wants to hire a roof to do legal work. Then again, who wants to hire a house. Give me a minute to come up with something else.

**Comment by BigActual** [comment]
Todo

**Comment by d4mation** [comment]
Do we have any ideas for how to handle this? It seems it got left at "We should change the image".

**Comment by d4mation** [comment]
Height is now user adjustable:

![image](https://user-images.githubusercontent.com/7770631/30712358-c5af2efa-9ed9-11e7-8262-b52f07a90024.png)

The background image is the Featured Image:

![image](https://user-images.githubusercontent.com/7770631/30712372-d08995e0-9ed9-11e7-8110-c9542063da83.png)

**Comment by d4mation** [comment]
@BigActual This correlates to **Homepage 2** and is on them. I added a height control and the image control has been there since launch.

**Comment by BigActual** [comment]
Remove this section completely. Take the call to action and place it in the green area, under the copy that is there.
So, to confirm, this means that the staff image and the green area will now be directly under the menu bar and the green area will now serve as the call to action button reading, "Learn more [about us]"

**Comment by BigActual** [comment]
You are not removing or replacing any text in the green area. Only adding the call to action under what's already there.

**Comment by d4mation** [comment]
These changes are now on Staging.
