### ISSUE TITLE
Remove the section on the home page for areas of practice 

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_INOSENCIO#13]
Remove this section completely and change the section below to white background
http://d.pr/i/pndLKM/5u3MgJrE
![image](https://user-images.githubusercontent.com/8271108/30665441-fe23d2c4-9e1e-11e7-9582-c8fa4fc6f8da.png)

**Comment by d4mation** [comment]
@BigActual This correlates to **Homepage 7**

According to the date on the PDF, these requests were made on September 26th. I removed the Areas of Practice from the Homepage Entirely on September 20th, so they shouldn't have even seen any of them on the Home Page.

Are they looking at the correct site? http://inosencio-com.realbig.staging.wpengine.com/
