### ISSUE TITLE
Blog 1: Blog page needs revamped

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_INOSENCIO#18]
> We think that the page dedicated to the “Blog” needs to be re-vamped. The
header on that page still says, “Starting a New Business.” We are interested in seeing
how our blog posts will appear on this page.

This is a misunderstanding on their part. The text that says "Starting a New Business" _**is**_ a Blog Post. It is the only Blog Post currently on the site.

![image](https://user-images.githubusercontent.com/7770631/30979623-33704196-a44c-11e7-8264-b4b4d69cd69a.png)

**Comment by BigActual** [comment]
I looked through this. What they're trying to see is how the blogroll and blog single will actually present on the screen. Their current archive shows only copy. No thumbnail from the featured image, not styling for the title or excerpt or read more button, no published date, etc. They want to create something like this, but styled to their theme: 
![image](https://user-images.githubusercontent.com/8271108/31105332-5606aef8-a7b1-11e7-98ca-e4056eaeaada.png)

and this for blog single (Which also, currently, makes no use of any fields of data, not even the featured image.)
![image](https://user-images.githubusercontent.com/8271108/31105391-d34e17f2-a7b1-11e7-9ae0-8814c0e68e97.png)

**Comment by d4mation** [comment]
Ah, I see. Interesting that there's no basic templating in place. I'll address this.
