### ISSUE TITLE
Firm Overview presentation of Highlight Quote needs styling

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_INOSENCIO#22]
- [x] Left align to fall in line with the left edge of the body copy
- [x] Create a Style that can also be selected in the WYSIWYG editor called Quote and use it here as well. 
  - Let's start with a font size and style equivalent to H2
  - When this style is chosen, place a nice set of pretty quotation marks to the left. Something big. Like the one in maroon: 
![image](https://user-images.githubusercontent.com/8271108/31103952-f9ee9af8-a7a7-11e7-9ead-fea98ed17db3.png)

**Comment by d4mation** [comment]
I've rigged this to work with the built-in "Blockquote" button in the WYSIWYG. I'm working on fixing the one in the Hero/CTA area for this page now.

![image](https://user-images.githubusercontent.com/7770631/31129605-114eabc2-a823-11e7-8a38-00b1ac4fe784.png)

![image](https://user-images.githubusercontent.com/7770631/31129712-5edd1a2c-a823-11e7-90f1-85a5d4f0ff1c.png)

**Comment by d4mation** [comment]
![image](https://user-images.githubusercontent.com/7770631/31130088-622afc5c-a824-11e7-9d16-9442af6d7aeb.png)
