### ISSUE TITLE
Move quotation Mark

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_INOSENCIO#26]
The right sid quotation mark needs to move to the end of the quote
![image](https://user-images.githubusercontent.com/8271108/31197163-3c01a238-a91e-11e7-9c8d-fc100d77fd2c.png)

**Comment by d4mation** [comment]
Unfortunately, the only way to reliably do this for _all_ `<blockquote>` elements was to not do it using CSS. So now Quotation Marks have to be added to the text directly, which means no more fancy looking quotation marks.

However, without the fancy ones was precisely how they had it before I enlarged it and positioned it correctly. I just wanted to add a little style. I agree on the odd appearance of the one on the right though. It looked better with just the one on the left, but the client didn't like that.
