### ISSUE TITLE
Add white space between body copy and the footer

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_INOSENCIO#27]
Let's stick a half inch or so of white space after the body copy on all pages, this will push the footer down a bit and allow the content to breathe just a touch.

**Comment by BigActual** [comment]
![image](https://user-images.githubusercontent.com/8271108/31197262-8ce717f0-a91e-11e7-8a8b-ecf6e108efb6.png)

**Comment by d4mation** [comment]
Good catch. This existed on most pages of the site, but was missing on the Home Page, the Contact Page, and the Firm Overview page.

Should be viewable on Staging now.
