### ISSUE TITLE
Add Edit Page icon on the top of the Practice Areas page

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM_TH_INOSENCIO#28]
The Edit Page link is missing here: http://inosencio-com.realbig.staging.wpengine.com/practice-areas/

**Comment by d4mation** [comment]
Misread this at first.

That isn't actually a Page but rather an Archive. If we want to put any kind of Content Editor at the top, I'll need to make it into a Page with a Page Template or a Shortcode to output the Practice Areas in the way that you see here.

**Comment by BigActual** [comment]
Ah, yes, I should have realized. Likely not required then.

**Comment by d4mation** [comment]
Well, that's an option now. I just changed it over to use a page template :+1:
