### ISSUE TITLE
Install Post Promoter Pro

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_INOSENCIO#4]

**Comment by d4mation** [comment]
Active on Staging: http://inosencio-com.realbig.staging.wpengine.com/

**Comment by BigActual** [comment]
The client is acquiring the license and will send details upon receipt.

**Comment by BigActual** [comment]
Is this installed and ready to activate?

**Comment by d4mation** [comment]
The plugin is installed and activated. The license however is not active. The license should not be activated until all of these changes are moved to Live.

**Comment by BigActual** [comment]
Thanks

**Comment by d4mation** [comment]
@BigActual The License Key will need to be added to Live
