### ISSUE TITLE
Staff on Home Page

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_INOSENCIO#5]
Use Attorneys CPT. Somewhat similar to http://www.fraserlawfirm.com/, but staying in-brand.

**Comment by d4mation** [comment]
Per @BigActual:

> There's literally no difference in my mind between what happens in the hero area and what happens in the Green bar underneath it. I'm talking about where it says "Welcome to Inosencio FIsk..." Seems like wasted area. 
>
> Would you be able to better achieve the goal of incorporating the new staff photographs, like the sample site they provided, by using that green bar as a backdrop for the content, "A small law firm with big capabilities, we ... decisions in their lawsuit or transaction." on the left with the images of the staff members on the right?
> 
> We could mess with or modify the title of this new green section, or just reuse "Welcome to Inosencio & Fisk"

**Comment by d4mation** [comment]
Since there are 4 of them, having them all in 1 row looks pretty nice in that area.

On mobile, I made it 2 per row so that they wouldn't get too small.

![image](https://user-images.githubusercontent.com/7770631/30224580-505333ea-949d-11e7-95cf-1fa8a820f18e.png)

**Comment by BigActual** [comment]
Have you added a gap between for some reason? I liked it better the other way.
![image](https://user-images.githubusercontent.com/8271108/30665276-765d0130-9e1e-11e7-8c5d-fd51a01d38ea.png)

**Comment by d4mation** [comment]
Uh, nope. On my screen it shows them as full-width in those containers. Might have to make an adjustment.
