### ISSUE TITLE
New Menu Structure

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_INOSENCIO#7]
Some content may not exist, so find a way that the new Page will be saved as a Draft, and on Publish, it will auto-add itself into the correct placement within the Menu.

* Alternative Dispute Resolution 
  * Arbitration 
  * Mediation

* Appeals

* Business Law
  * Acquisitions 
  * Asset Purchases / Sales Transactions
  * Business Disputes
  * Business Dissolution
  * Business Insurance Coverage and Disputes
  * Business Succession Planning
  * Change of Ownership or Corporate Structure
  * Commercial Transactions
  * Condominium Associations
  * Consulting Agreements
  * Contract Negotiation and Disputes
  * Corporate Reorganizations
  * Corporate Transactions
  * Employment Agreements
  * Employment and Labor Issues
  * Formation of corporations
  * Formation of limited liability companies (LLC formation)
  * Formation of non-profit entities
  * 501(c)(3) / Tax Status Applications 
  * General Business Matters
  * Independent Contractor Agreements
  * Mergers
  * New business startups
  * Non-Complete Agreements 
  * Non-Disclosure Agreements
  * Non-Solicitation Agreements
  * Partnerships
  * State Licensing Issues 
  * Tortious Interference

* Construction Law
  * Bond Claims / Surety Claims
  * Claims of Lien
  * Commercial Construction Contracts
  * Condominium / development documents
  * Construction lien documents and litigations
  * Construction litigation (residential and commercial)
  * Contract disputes
  * Delay claims
  * Independent Contractor Agreements
  * Residential Construction Contracts 
  * Subcontractor Agreements 
  * Warranty claims

* Intellectual Property
  * Contracts
  * Protecting Trade Secrets
  * Trademarks / Service Marks 

* Litigation 
  * Breach of contract claims
  * Breach of warranty claims
  * Business, Corporation, LLC and Partnership disputes
  * Business Torts
  * Construction litigation
  * Construction lien litigation
  * Debt Collection 
  * Domestication of foreign judgments
  * False Claims / Whistleblower matters
  * Federal Court litigations
  * General Civil litigation
  * Insurance coverage disputes 
  * Landlord-Tenant litigation
  * Medical Malpractice
  * Personal Injury litigation
  * Probate Litigation 
  * Real Estate litigation
  * Seller’s Disclosure disputes
  * Tortious Interference
  * Wrongful Death

* Probate and Estates
  * Conservatorships 
  * Estate Administration
  * Guardianships
  * Power of Attorney
  * Probate Disputes
  * Trusts
  * Wills 

* Real Estate Law
  * Boundary disputes
  * Condominium development issues
  * Deeds
  * Easements
  * Foreclosures and forfeitures
  * Lake access / riparian rights
  * Land Contracts
  * Landlord-Tenant matters
  * Leases (Commercial and Residential)
  * Litigation
  * Mortgages
  * Property insurance coverage disputes
  * Purchase Agreements
  * Quiet Title Actions 
  * Real Property Tax Assessment Appeals
  * Seller’s Disclosure disputes

**Comment by d4mation** [comment]
Started to work on this since I'm waiting on #9 before starting on #5 and #8.

@BigActual Two things to note:

1. The theme currently does not support sub-menus. I'll need to add this in
2. Holy moly, I only just realized how many sub-menu items there were. There is no way these will all fit on screen. Are they sure about this?

**Comment by BigActual** [comment]
I'll have to ask.

**Comment by d4mation** [comment]
I'm having to update this site from Foundation 5 to Foundation 6 in order to get sub-menus working in any reasonable fashion. This is on a separate branch, so it doesn't include the changes from #9.

This is such a huge change, however, due to all the major adjustments I'm having to make to template files and the build process, that I'll basically need to re-do #9 once that is approved if we go toward using/needing these sub-menus. The number of merge conflicts that would occur would be much more head-ache inducing than re-doing it 😧 

I adjusted the spacing for the header area while doing this as well and I think it helps overall moving toward the ideas in #9.

![image](https://user-images.githubusercontent.com/7770631/30179130-560f7844-93d9-11e7-9c44-f3773bcd060e.png)

**Comment by BigActual** [comment]
Yes, as you may have figured out, I'm a fan of white space, so feel free to add space between items. It's calming.

**Comment by BigActual** [comment]
Sorry to hear that it's causing extra work. The end product will be awesome.

**Comment by d4mation** [comment]
Just tested: Making a Page, assigning it to a Menu, and then changing it to "Draft" status still leaves it in the Menu. So there would be a _ton_ of broken links in the Menu if we did this.

It seems overly complicated the more I think about this, actually. Why not just add them to the Menu as they are created? The WordPress Menu editor in the Dashboard isn't bad at all, and the one in the Customizer is even better.

Unless there is a 3rd party solution out there somewhere to accomplish this (Scheduled menu items? I don't know, something may exist), this appears like it will be a _huge_ time sink. More so than migrating to Foundation 6 has been to make the Dropdown Menus even a potential.

**Comment by d4mation** [comment]
https://wordpress.org/plugins/hide-drafts-in-menus/

Welp, look at that. **_Exactly_** what we needed.

**Comment by d4mation** [comment]
@BigActual I'll install this plugin on Staging, but we should confirm the Menu Structure again first since as I said, there are far too many in a single Submenu for it to be usable as it is.

**Comment by d4mation** [comment]
I made a separate branch to include these changes as well as the changes from #9. That way they could be seen together.

The changes here are mostly just moving to Foundation 6 to properly support the Dropdown Menus. However, it also had some nice side effects like drastically improving the Mobile Menu. 

From here, it should just be handling the changes for #8 and #5.

@BigActual Did we ever get approval on the changes for #9 from Bruce?

**Comment by BigActual** [comment]
Client has been informed of the requirements to pair down the menu. He will send it back shortly with modifications. (3 or 4 max per).

**Comment by BigActual** [comment]
- Alternative Dispute Resolution
     - Arbitration
     - Mediation
 
- Appeals
 
- Business Law
     - Acquisitions / Reorganizations
     - Business Disputes
     - Document prep
     - 501(c)(3) / Tax Status Applications
     - Business formation and dissolution
 
- Construction Law 
     - Bond Claims / Surety Claims
     - Claims of Lien
     - Construction litigation (residential and commercial)
     - Contract disputes
     - Contract and document prep
 
- Intellectual Property 
     - Contracts
     - Protecting Trade Secrets
     - Trademarks / Service Marks
 
- Litigation 
     - Business, Corporation, LLC and Partnership disputes
     - Debt Collection
     - False Claims / Whistleblower matters
     - Personal Injury / Wrongful Death
     - Real Estate litigation
 
- Medical Malpractice

- Probate and Estate 
     - Conservatorships / Guardianships
     - Estate Administration
     - Power of Attorney
     - Probate Disputes
     - Estate Planning
 
- Real Estate Law
     - Boundary and easement disputes
     - Foreclosures and forfeitures
     - Lake access rights / riparian rights
     - Landlord-Tenant matters
     - Document prep

**Comment by d4mation** [comment]
Another problem that I guess I didn't mention: There is not enough space for that many TOP LEVEL Menu Items either. At least not on my screen.

The Blue area shows the available space and the Orange area shows the Margin on either side. The Green is Padding around the elements. We could remove from the Margin and Padding to make it up to full-width, but that may only make enough room for one or two more Top-Level Menu Items.

![image](https://user-images.githubusercontent.com/7770631/30215470-0ea0dc64-947e-11e7-93bd-f78faf7a91e6.png)

**Comment by d4mation** [comment]
The logo could also be made smaller I suppose, but the "Attorneys at Law" text could be easily lost if it were made too small.

**Comment by BigActual** [comment]
What about a Mega/Uber Menu

**Comment by d4mation** [comment]
That could solve having an insane amount of submenu items, but we'd still have the same problem with the number of top-level items.

**Comment by BigActual** [comment]
Or dropping it down onto a line above or below the logo. Probably the easiest option

**Comment by BigActual** [comment]
Separate menu for areas of practice? Maybe just that goes on a top level menu?

**Comment by d4mation** [comment]
We could drop it down a line, but then we'll have to do a lot of restructuring of the Header area to make it look good.

![image](https://user-images.githubusercontent.com/7770631/30216434-fcd764e6-9480-11e7-922d-5ab98c417011.png)

I think placing the second revision of the menu below "Areas of Practice" is the best option. That will conserve the most space and require the least amount of rework. In fact, it may have been the goal originally considering none of the other Top-Level Items currently there are in the new Menu Structure above.

**Comment by BigActual** [comment]
HOw did the other firm that was presented as an example deal with this?

**Comment by d4mation** [comment]
Same as how we are really. 

![image](https://user-images.githubusercontent.com/7770631/30217773-2912e522-9485-11e7-8a0b-a4ef860023f9.png)

**Comment by BigActual** [comment]
Follow their lead then.

**Comment by d4mation** [comment]
I wanted to make a note of this here:

The page for "Litigation" may want to be filled out before this goes Live. This is because as it is now, I _have_ to Draft "Personal Injury" and "Wrongful Death", otherwise they get forced up to the Top Level. I guess since its direct Parent, "Litigation", is a Draft it gets confused and forces it all the way to the Top despite it being a couple levels deep in the Navigation.

If "Litigation" were to be Published, we could allow "Personal Injury" and "Wrongful Death" to stay Published without breaking the Navigation.

![image](https://user-images.githubusercontent.com/7770631/30218632-812dc9be-9487-11e7-9c83-b699cd1153b2.png)

![image](https://user-images.githubusercontent.com/7770631/30218609-745aaefa-9487-11e7-9d93-32d5e978268a.png)

**Comment by d4mation** [comment]
"Personal Injury" and "Wrongful Death" are listed on Bruce's page and on the Home Page, and by Drafting them, they get removed from those pages. So this effects more than just the Navigation unfortunately.

**Comment by d4mation** [comment]
These are all added in now. Only the Published Practice Areas show, but the full menu can be viewed here: http://inosencio-com.realbig.staging.wpengine.com/wp-admin/nav-menus.php?action=edit&menu=71

![image](https://user-images.githubusercontent.com/7770631/30219132-1f09c4ac-9489-11e7-8678-ede399f8c5c9.png)

When new Menu Items are Published, it will place them in a deeper sub-menu to the side just like in the example site.

![image](https://user-images.githubusercontent.com/7770631/30219279-921cda9c-9489-11e7-94ed-75dc4d722a29.png)

---

# Like I mentioned above, "Litigations" should be Published before this goes Live. This way "Personal Injury" and "Wrongful Death" can be Re-Published.

**Comment by BigActual** [comment]
I've created dummy copy and shared the page with Bruce to ask for clarification.

**Comment by d4mation** [comment]
@BigActual This correlates to **Homepage 4**.

It does match the menu structure. Those pages are just currently drafted as they have no content. Once they are published, they will show automatically in their correct locations in the menu.

**Comment by d4mation** [comment]
This actually correlates to a _ton_ of the bullet points in here. I am not sure if they were aware that they cannot be Published (And therefore show up in any lists or in any menus) until they have Content.

The Practice Areas exist in the Database, but they will not show until there is Content.
