### ISSUE TITLE
On-Brand Suggestions for Home Page

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_INOSENCIO#9]
> Look at the weight of the Blue and Green graphics on the site. It's pretty heavy handed and leans toward something more pretentious than their brand would actually suggest. Could you please make some suggestions for how to take that toward the neighbor and the innocent instead. I'm only looking for minor tweaks that could have positive impact.

Throwing in ideas here:

* The "V"-shaped cutout and texture across many elements on the site elicits a feeling of a fancy, die-cut business card. Tossing those out to go for something more simple may help.
  * Removing the "V" would also allow each section with a "V" to be smaller, which would mean for those colored sections they would automatically have less weight on the page.
![image](https://user-images.githubusercontent.com/7770631/30080496-d1ba3be8-9251-11e7-9fef-224e9cec7d2a.png)

* In order to balance out colors some more on the Home page, making the "The areas in which we practice include/We’ve also represented clients concerning" section have a white background with green accents instead of green with white accents may help. This is a very, very large section that currently is adding the most weight to the page outside of the Hero at the top.

* The use of "[Raleway](https://fonts.google.com/specimen/Raleway)" as a Header font does not help. It should be changed out for something more simple. The `W` in Raleway really harms the branding if the goal is neighbor/innocent. It screams business card similar to the first bullet point above.
![image](https://user-images.githubusercontent.com/7770631/30080737-b3bbde0c-9252-11e7-9f89-dada18e963cd.png)

**Comment by BigActual** [comment]
Do you have a mockup I can share with the client?

**Comment by BigActual** [comment]
Heading out soon. Go ahead and shoot this over to me, and I'll get back to you from on the road.

**Comment by d4mation** [comment]
I don't have a mockup right now&mdash;these were just ideas. I may not get to this until later today :/

**Comment by d4mation** [comment]
@BigActual 

It was much easier to code this out that to make a Photoshop/in-browser mock.

I have these changes as part of the `issue/9/on-brand` branch and that is currently on Staging.

I did the following:
- Removed the "V" and the texture from those sections
- Changed the Header Font Family to Open Sans and the Body Font Family to Georgia (a Serif Font). This helps differentiate the body copy from the headers and also increases readability for the body copy
- Made the section color changes I outlined above. Basically just swapped the background colors of the two sections
- Adjusted some spacing throughout to make things more "light"

The major heavy areas now are all "above the fold" which is unfortunate. The Hero and the section right below it are full-width photos which really pulls everything down. I don't see the Hero changing, but the other section could possibly be replaced by #5.

Like I mentioned on Slack, I wanted to get this done first so that while working on #5 and #8 we wouldn't end up making a million revisions while trying to match it up with any major changes to the home page. This theme isn't super flexible when it comes to global colors/spacing, so most changes have to be made per-section.

Let me know what you think and if there's any other tweaks you can think of. You had said we were looking more for minor tweaks so I didn't want to rebuild complete sections while doing this.

http://inosencio-com.realbig.staging.wpengine.com/

**Comment by BigActual** [comment]
Yes, Much better, can you take the double pinstripe around the header of each section down to a single underline?

**Comment by d4mation** [comment]
From Slack:

> Eric Defore [9:42 AM] 
> Just pushed the change for single underlines on the headers

**Comment by BigActual** [comment]
Client approved.
